### ISSUE TITLE
Why

### ISSUE THREAD

**Issue by omxpro** [yTax/rdpgrabber#1]
Why does it get my GitHub account deleted, any tips on making it work perfectly

**Comment by yTax** [comment]
just tried the script again and its still working fine, im pretty sure you're doing something wrong.

**Comment by omxpro** [comment]
Steps I did

• Get a new browser and a VPN
• make a new GitHub acc with 6 month old Gmail 
• browse on it for 2 hours
• fork the repo
• the ngrok stuff (adding secrets stuff)
• turned on the actions
• used the ip and pass to login
• after 15m my account has been suspended

**Comment by omxpro** [comment]
Could it be because I have 2 accs on same IP/Device agent

**Comment by yTax** [comment]
might be cause of that, send me your discord i could hop on a call with you and help you figure it out if you want to.

**Comment by omxpro** [comment]
Hey Um, I really don't do calls, I only do screen share and Litsening to you but not responding

**Comment by omxpro** [comment]
OmsenjaliaYT#7508 btw

**Comment by yTax** [comment]
just added you, might be because you're on mobile, i dont remember trying this on my phone

**Comment by omxpro** [comment]
I really don't have a PC because I am from a semi poor family in India that's why I needed this rdp, can you try it on mobile?

**Comment by yTax** [comment]
thread closed: user ip/useragent is banned

**Comment by omxpro** [comment]
What if I try orbot browser (it changes user agent and gives you a dedicated ip)
